name: Caller workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow in test"

  reviews:
    needs: test
    runs-on: ubuntu-latest
    environment: Review
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #   - name: Echo
    #     run: echo "Welcome to the caller workflow in reviews"
    #   - name: file structure
    #     run: ls -R
    uses: ./.github/workflows/called_workflow.yml
    with:
      workflow_id: multistage_workflow reviews
      workflow_input: Input for the called workflow

  deploy:
    needs: reviews
    uses: ./.github/workflows/called_workflow.yml
    with:
      workflow_id: multistage_workflow deploy
      workflow_input: Input for the called workflow
  #   environment: Staging
  
  production:
    needs: deploy
    uses: ./.github/workflows/called_workflow.yml
    with:
      workflow_id: multistage_workflow production
      workflow_input: Input for the called workflow
  #   environment: Production
  
  Log_test:
    needs: [test]
    runs-on: ubuntu-latest
    environment: Review
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In Log"

  Log_reviews:
    needs: [test, reviews]
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In Log"

  Log:
    needs: [test, reviews, deploy]
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In Log"

  
    