name: Caller workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In test"
    
  reviews:
    needs: test
    uses: ./.github/workflows/called_workflow.yml
    environment: Review
  # deploy:
  #   needs: reviews
  #   uses: ./.github/workflows/called_workflow.yml
  #   environment: Staging
  
  # production:
  #   needs: deploy
  #   uses: ./.github/workflows/called_workflow.yml
  #   environment: Production
  
  # Log:
  #   needs: [test, reviews, deploy]
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Echo
        # run: echo "Welcome to the caller workflow In Log"

  
    