name: Called Workflow
on:
  workflow_call:
    inputs:
      workflow_id:
        description: 'ID of the workflow to call'
        required: true
        default: 'multistage_workflow'
        type: string
      workflow_input:
        description: 'Input for the called workflow'
        required: true
        default: 'Input for the called workflow'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set_output.outputs.output1 }}
      output2: ${{ steps.set_output2.outputs.output2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run called workflow
        run: echo "Welcome to the called workflow"
      - name: Echo
        run: echo "Input for the called workflow is ${{ inputs.workflow_input }}"
      - name: Echo
        run: echo "Workflow ID is ${{ inputs.workflow_id }}"
      - name: Echo
        id: set_output
        run: echo "output1=Sucess1" >> $GITHUB_OUTPUT
      - name: Echo
        id: set_output2
        run: echo "output2=Sucess2" >> $GITHUB_OUTPUT
