name: Caller workflow For Reusable workflow example
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In test"
    
  reviews:
    needs: test
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In reviews"
  
  deploy:
    needs: reviews
    environment: Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In deploy"
  
  production:
    needs: deploy
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Welcome to the caller workflow In production"

  
    